### PR TITLE
Small issues

### LINKED ISSUE #64: Long file names do not work well in the nav bar
Probably need to just show the first `n` characters in order to ensure that spacing works correctly

### LINKED ISSUE #67: Creating a new view should open the view
- Currently when a new view is created nothing shows up

https://user-images.githubusercontent.com/9358846/106970004-ffe56880-6719-11eb-9378-0d9ee845bb1d.mov

### LINKED ISSUE #68: Two Consecutive Saves Is causing problems with the doc
On Frontend, immediately disable save button on click to prevent another call.

### LINKED ISSUE #74: Navbar file names don't reflect updates from rename
- After renaming the navbar does not show the updated file / view name

image

### PR DESCRIPTION
**Pull request by aravind-segu**
Closes #74 
Closes #68 
Closes #67 
Closes #64

### CODE REVIEW

File: src/components/Navigator.js [hunk 1]
```diff
@@ -393,6 +399,7 @@ class Navigator extends React.Component {
       });
       return;
     }
+    store.dispatch(setCurrentOpenFileNameAction({sourceName: newName, viewName: ''}));
```
Comment (Shehan29) [inline src/components/Navigator.js:402]: Do we need a similar line for renaming view files or is that covered somewhere else?

**Review by Shehan29 — APPROVED** [review]
