### PR TITLE
Clear Redux store on signout

### LINKED ISSUE #98: Last open document ID persists when a user logs out
I get a "failed to get source" toast when I switch from accounts `a` to `b`.  This happens because yada tries to open a file from  `a` in when I first switch to `b`. We should clear all `localStorage` when a user signs out. Maybe even when their authentication fails as they could sign in to a new account there?

### PR DESCRIPTION
**Pull request by aravind-segu**
Closes #98

### CODE REVIEW

File: src/reducers/CurrentOpenFileState.js [hunk 1]
```diff
@@ -29,17 +32,39 @@ const initialFileName = {
...
+
 const SET_CURRENT_OPEN_FILE_ID_ACTION_TYPE = 'currentOpenFileId/set';
 export const setCurrentOpenFileIdAction = fileId => ({ type: SET_CURRENT_OPEN_FILE_ID_ACTION_TYPE, fileId });
-export const currentOpenFileIdReducer = (state = initialFileId, action) =>
-  action.type !== SET_CURRENT_OPEN_FILE_ID_ACTION_TYPE || !validateHasFileIdObj(action)
+export const currentOpenFileIdReducer = (state = initialFileId, action) => {
+  if (action.type === SIGNOUT){
+    console.log("setting to empty file id");
+    return emptyFileId
+  }else{
```
Comment (AkshayPall) [inline src/reducers/CurrentOpenFileState.js:52]: huh... how did this pass local formatting?!

Comment (AkshayPall) [reply src/reducers/CurrentOpenFileState.js:52]: ah I see the formatter broke in the last PR. It's fine - we can reformat all the code once this is merged

**Review by AkshayPall — APPROVED** [review]
